version: "3.9"

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=employee_management'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'
    env_file: .env
    depends_on:
      - postgres
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/employee_management'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=1234'
      - 'KAFKA_ADDRESS=kafka:9092'
networks:
  default:
    name: my-network
    driver: bridge
    external: true